# Generated by Django 5.2.6 on 2025-11-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='evento',
            name='voluntarios',
        ),
        migrations.AddField(
            model_name='evento',
            name='voluntarios',
            field=models.IntegerField(default=0),
        ),
    ]
