# Generated by Django 5.2.8 on 2025-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options_alter_evento_titulo_and_more'),
        ('voluntarios', '0002_alter_voluntario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='voluntarios',
        ),
        migrations.AddField(
            model_name='evento',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='voluntarios.voluntario'),
        ),
    ]
