# Generated by Django 5.2.6 on 2025-11-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
    ]
